modLoader="javafml"
loaderVersion="[47,)"
license="LGPL-3.0-only"
[[mods]]
modId="panopticon"
version="1.0"
displayName="Panopticon"
authors="Mokich"
logoFile="logo.png"
displayTest="IGNORE_SERVER_VERSION"
description=""

[[dependencies."panopticon"]]
   modId="forge"
   mandatory=true
   versionRange="[47,)"
   ordering="NONE"
   side="SERVER"
[[dependencies."panopticon"]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.1,1.21)"
   ordering="NONE"
   side="SERVER"