plugins {
    id 'fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

repositories {
    maven { url = 'https://maven.blamejared.com' }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 17
    options.encoding = 'UTF-8'
}

tasks.named('remapJar') {
    archiveFileName = "${mod_name}-${mod_version}-${loader_name}-${minecraft_version}.jar"
}
apply from: file('../stampDates.gradle')
