org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false
net.minecraftforge.gradle.merge-source-sets=true
org.gradle.java.home=C:/Games/ggg/jdk25-portable
org.gradle.java.installations.paths=C:/Games/ggg/jdk25-portable

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
forge_version=64.1.0
forge_version_range=[64,)
loader_version_range=[64,)
loader_name=Forge
mapping_channel=official
mapping_version=26.1.2

mod_id=panopticon
mod_name=Panopticon
mod_license=LGPL-3.0-only
mod_version=1.08
mod_group_id=net.mokich.panopticon
mod_authors=Mokich
mod_description=
org.gradle.java.installations.auto-detect=false
