org.gradle.jvmargs=-Xmx5G
org.gradle.java.home=C:/Games/ggg/jdk25-portable
org.gradle.java.installations.paths=C:/Games/ggg/jdk25-portable
org.gradle.daemon=false

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neoforge_version=26.1.2.87
neoforge_version_range=[26.1.0,)
loader_version_range=[4,)

mod_id=panopticon
mod_name=Panopticon
mod_license=LGPL-3.0-only
mod_version=1.08
mod_group_id=net.mokich.panopticon
mod_authors=Mokich
mod_description=
loader_name=NeoForge
